ALTER TABLE db_aptitude MODIFY version INTEGER UNSIGNED;
ALTER TABLE db_embarcation MODIFY version INTEGER UNSIGNED;
ALTER TABLE db_fiche_securite MODIFY version INTEGER UNSIGNED;
ALTER TABLE db_moniteur MODIFY version INTEGER UNSIGNED;
ALTER TABLE db_palanquee MODIFY version INTEGER UNSIGNED;
ALTER TABLE db_plongeur MODIFY version INTEGER UNSIGNED;
ALTER TABLE db_utilisateur MODIFY version INTEGER UNSIGNED;